theme: jekyll-theme-minimal
title: Cloud Migration Dallas
description: Expert IT guidance and resources for Dallas-Fort Worth businesses
google_analytics: # Add your GA tracking ID here
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
